#!/usr/bin/env python3
"""
检查 Mintlify 配置 - 理解两个 mint.json 的关系
"""

print("=" * 70)
print("Mintlify 配置文件说明")
print("=" * 70)
print()

print("当前有两个 mint.json 文件：")
print()
print("1. 根目录的 mint.json")
print("   位置: /latex-mcp-knowledge/mint.json")
print("   路径格式: mintlify-docs/introduction")
print("   用途: 当 Mintlify 从「根目录」部署时使用")
print()
print("2. 子目录的 mint.json")
print("   位置: /latex-mcp-knowledge/mintlify-docs/mint.json")
print("   路径格式: introduction")
print("   用途: 当 Mintlify 从「mintlify-docs 目录」部署时使用")
print()

print("=" * 70)
print("关键问题：Mintlify 实际使用哪个文件？")
print("=" * 70)
print()

print("这取决于 Mintlify Dashboard 中的「Docs Directory」设置：")
print()
print("情况A：Docs Directory = '/' 或留空")
print("  → 使用: 根目录的 mint.json")
print("  → URL 路径会包含 /mintlify-docs/")
print("  → 示例: https://xxx.mintlify.app/mintlify-docs/introduction")
print()
print("情况B：Docs Directory = 'mintlify-docs'")
print("  → 使用: mintlify-docs/mint.json")
print("  → URL 路径不包含 /mintlify-docs/")
print("  → 示例: https://xxx.mintlify.app/introduction")
print()

print("=" * 70)
print("当前状态分析")
print("=" * 70)
print()

print("您访问的 URL: https://baidu-a3d5180c.mintlify.app/mintlify-docs/introduction")
print()
print("分析：URL 包含 /mintlify-docs/，说明：")
print("  ✓ Mintlify 从「根目录」部署")
print("  ✓ 应该读取「根目录的 mint.json」")
print("  ✓ 我们已经更新了根目录的 mint.json（V2.0，6812项）")
print()

print("=" * 70)
print("为什么还显示旧数据？")
print("=" * 70)
print()

print("可能的原因：")
print("1. Mintlify 缓存未刷新（最常见）")
print("   → 等待 5-10 分钟自动部署")
print("   → 或在 Dashboard 手动触发重新部署")
print()
print("2. Git 推送延迟")
print("   → 检查 GitHub 是否已有最新提交")
print()
print("3. Mintlify Webhook 未触发")
print("   → 检查 Dashboard 的部署历史")
print()

print("=" * 70)
print("下一步操作")
print("=" * 70)
print()
print("1. 访问 Mintlify Dashboard: https://dashboard.mintlify.com")
print("2. 选择项目: latex-mcp-knowledge")
print("3. 查看 Deployments 页面，确认最新部署时间")
print("4. 如果没有新部署，点击「Trigger Deploy」手动触发")
print()
